### ISSUE TITLE
Build fails on Raspbian

### ISSUE THREAD

**Issue by maikschneider** [phorque/node-epeg#4]
I'm unable to install the node package on my RaspberryPi with

```
node @v0.10.28
npm @1.4.9
epeg @0.9.1.042
```

The install error:

```
pi@raspberrypi ~/photobox_node/node_modules/node-epeg $ npm install
npm http GET http://registry.npmjs.org/mocha
npm http GET http://registry.npmjs.org/expect.js
npm http 304 http://registry.npmjs.org/mocha
npm http 304 http://registry.npmjs.org/expect.js
npm http GET http://registry.npmjs.org/diff
npm http GET http://registry.npmjs.org/debug
npm http GET http://registry.npmjs.org/growl
npm http GET http://registry.npmjs.org/jade
npm http GET http://registry.npmjs.org/mkdirp
npm http GET http://registry.npmjs.org/commander
npm http GET http://registry.npmjs.org/glob
npm http 304 http://registry.npmjs.org/diff
npm http 304 http://registry.npmjs.org/debug
npm http 304 http://registry.npmjs.org/growl
npm http 304 http://registry.npmjs.org/jade
npm http 304 http://registry.npmjs.org/mkdirp
npm http 304 http://registry.npmjs.org/glob
npm http 304 http://registry.npmjs.org/commander
npm http GET http://registry.npmjs.org/ms
npm http 304 http://registry.npmjs.org/ms
npm http GET http://registry.npmjs.org/graceful-fs
npm http GET http://registry.npmjs.org/inherits
npm http GET http://registry.npmjs.org/minimatch
npm http 304 http://registry.npmjs.org/graceful-fs
npm http 304 http://registry.npmjs.org/inherits
npm http 304 http://registry.npmjs.org/minimatch
npm http GET http://registry.npmjs.org/mkdirp
npm http 304 http://registry.npmjs.org/mkdirp
npm http GET http://registry.npmjs.org/sigmund
npm http GET http://registry.npmjs.org/lru-cache
npm http 304 http://registry.npmjs.org/sigmund
npm http 304 http://registry.npmjs.org/lru-cache

> epeg@0.7.0 install /home/pi/photobox_node/node_modules/node-epeg
> node-gyp rebuild

make: Entering directory `/home/pi/photobox_node/node_modules/node-epeg/build'
  CXX(target) Release/obj.target/epeg/src/epeg.o
In file included from ../src/epeg.cc:4:0:
../src/Image.h:37:26: error: ISO C++ forbids initialization of member ‘scaled’ [-fpermissive]
../src/Image.h:37:26: error: making ‘scaled’ static [-fpermissive]
../src/Image.h:37:26: error: ISO C++ forbids in-class initialization of non-const static member ‘scaled’
../src/Image.h:38:26: error: ISO C++ forbids initialization of member ‘croped’ [-fpermissive]
../src/Image.h:38:26: error: making ‘croped’ static [-fpermissive]
../src/Image.h:38:26: error: ISO C++ forbids in-class initialization of non-const static member ‘croped’
make: *** [Release/obj.target/epeg/src/epeg.o] Error 1
make: Leaving directory `/home/pi/photobox_node/node_modules/node-epeg/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.12.20+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/photobox_node/node_modules/node-epeg
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok

npm ERR! epeg@0.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epeg@0.7.0 install script.
npm ERR! This is most likely a problem with the epeg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls epeg
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.12.20+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/pi/photobox_node/node_modules/node-epeg
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/photobox_node/node_modules/node-epeg/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mzozo95** [comment]
Any update? It fails at mee too. I have NodeJs v0.12.6 on raspian in a raspberri pi B+.

**Comment by phorque** [comment]
Sorry guys, I won't have time nor the motivation to work on this D:
